use indoc::indoc;

pub(crate) fn fake_project() -> String {
    indoc! {r#" {
            "self_link": "https://api.launchpad.net/1.0/nova",
            "web_link": "https://launchpad.net/nova",
            "resource_type_link": "https://api.launchpad.net/1.0/#project",
            "official_answers": false,
            "official_blueprints": true,
            "official_codehosting": false,
            "official_bugs": true,
            "information_type": "Public",
            "active": true,
            "bug_reporting_guidelines": "!!!!!!!!!!!!!!!!!!!!!!!!! READ THIS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nEach bug report needs to provide a minimum of information without\nwe are not able to address the issue you observed. It is crucial \nfor other developers to have this information. You can use the \ntemplate below, which asks for this information. \n\n\"Request for Feature Enhancements\" (RFEs) are collected:\n* with the blueprint process [1][2][3] (if you're a developer) OR \n* via the liason with the operator (ops) community [4].\nThis means \"wishlist\" bugs won't get any attention anymore.\n\nYou can ask in the #openstack-nova IRC channel on freenode, if you have questions about this.\n\nReferences:\n[1] https://blueprints.launchpad.net/nova/\n[2] https://github.com/openstack/nova-specs\n[3] https://wiki.openstack.org/wiki/Blueprints\n[4] http://lists.openstack.org/pipermail/openstack-operators/2016-March/010007.html\n\n!!!!!!!!!!!!!!!!!!!!!!!!! READ THIS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n\n\nDescription\n===========\nSome prose which explains more in detail what this bug report is\nabout. If the headline of this report is descriptive enough, skip \nthis section.\n\nSteps to reproduce\n==================\nA chronological list of steps which will bring off the\nissue you noticed:\n* I did X\n* then I did Y\n* then I did Z\nA list of openstack client commands (with correct argument value)\nwould be the most descriptive example. To get more information use:\n\n    $ nova --debug <command> <arg1> <arg2=value>\n    or\n    $ openstack --debug <command> <arg1> <arg2=value>\n\nExpected result\n===============\nAfter the execution of the steps above, what should have\nhappened if the issue wasn't present?\n\nActual result\n=============\nWhat happened instead of the expected result?\nHow did the issue look like?\n\nEnvironment\n===========\n1. Exact version of OpenStack you are running. See the following\n  list for all releases: http://docs.openstack.org/releases/\n\n   If this is from a distro please provide\n       $ dpkg -l | grep nova\n       or\n       $ rpm -qa | grep nova\n   If this is from git, please provide\n       $ git log -1\n\n2. Which hypervisor did you use? \n   (For example: Libvirt + KVM, Libvirt + XEN, Hyper-V, PowerKVM, ...)\n   What's the version of that?\n\n2. Which storage type did you use?\n   (For example: Ceph, LVM, GPFS, ...)\n   What's the version of that?\n\n3. Which networking type did you use?\n   (For example: nova-network, Neutron with OpenVSwitch, ...)\n\nLogs & Configs\n==============\nThe tool *sosreport* has support for some OpenStack projects.\nIt's worth having a look at it. For example, if you want to collect\nthe logs of a compute node you would execute:\n\n   $ sudo sosreport -o openstack_nova --batch\n\non that compute node. Attach the logs to this bug report. Please \nconsider that these logs need to be collected in \"DEBUG\" mode.\n\nFor tips on reporting VMware virt driver bugs, please see this doc: https://docs.openstack.org/nova/latest/admin/configuration/hypervisor-vmware.html#troubleshooting",
            "content_templates": null,
            "bug_reported_acknowledgement": "Thanks for filing this bug report. Please double-check if you provided the minimum of needed information in the description of this report. The last current bug report template can be found at: https://wiki.openstack.org/wiki/Nova/BugsTeam/BugReportTemplate",
            "official_bug_tags": [
                "api",
                "api-ref",
                "availability-zones",
                "cells",
                "ceph",
                "cinder",
                "compute",
                "conductor",
                "config",
                "console",
                "cyborg",
                "db",
                "doc",
                "dpdk",
                "ec2",
                "evacuate",
                "fault-injection",
                "gate-failure",
                "glance",
                "i18n",
                "image-cache",
                "in-stable-liberty",
                "in-stable-newton",
                "in-stable-ocata",
                "ironic",
                "libvirt",
                "live-migration",
                "low-hanging-fruit",
                "lxc",
                "metadata",
                "network",
                "neutron",
                "newton-backport-potential",
                "nfs",
                "notifications",
                "nova-manage",
                "nova-network",
                "numa",
                "ops",
                "oslo",
                "pci",
                "performance",
                "placement",
                "policy",
                "postgresql",
                "powervm",
                "privsep",
                "quotas",
                "race-condition",
                "rbac",
                "reboot",
                "rebuild",
                "rescue",
                "resize",
                "resource-tracker",
                "rfe",
                "rootwrap",
                "s390x",
                "scheduler",
                "sdk",
                "security",
                "security-groups",
                "serviceability",
                "sev",
                "shared-storage",
                "shelve",
                "snapshot",
                "stacktrace",
                "testing",
                "unified-objects",
                "upgrade",
                "vgpu",
                "vmware",
                "volumes",
                "zvm"
            ],
            "recipes_collection_link": "https://api.launchpad.net/1.0/nova/recipes",
            "webhooks_collection_link": "https://api.launchpad.net/1.0/nova/webhooks",
            "bug_supervisor_link": "https://api.launchpad.net/1.0/~nova-bugs",
            "active_milestones_collection_link": "https://api.launchpad.net/1.0/nova/active_milestones",
            "all_milestones_collection_link": "https://api.launchpad.net/1.0/nova/all_milestones",
            "qualifies_for_free_hosting": true,
            "reviewer_whiteboard": "tag:launchpad.net:2008:redacted",
            "is_permitted": "tag:launchpad.net:2008:redacted",
            "project_reviewed": "tag:launchpad.net:2008:redacted",
            "license_approved": "tag:launchpad.net:2008:redacted",
            "private": false,
            "display_name": "OpenStack Compute (nova)",
            "icon_link": "https://api.launchpad.net/1.0/nova/icon",
            "logo_link": "https://api.launchpad.net/1.0/nova/logo",
            "name": "nova",
            "owner_link": "https://api.launchpad.net/1.0/~nova-drivers",
            "project_group_link": "https://api.launchpad.net/1.0/openstack",
            "title": "OpenStack Compute (nova)",
            "registrant_link": "https://api.launchpad.net/1.0/~anotherjesse",
            "driver_link": "https://api.launchpad.net/1.0/~nova-drivers",
            "summary": "Nova is a cloud computing fabric controller (the main part of an IaaS system). It is written in Python.\n",
            "description": "Get the code: https://git.openstack.org/cgit/openstack/nova\n\nCode reviews - https://review.openstack.org\nContinuous Build/Integration - http://status.openstack.org/zuul/?openstack/nova\n\nDocumentation - https://docs.openstack.org/nova/\nIRC - #openstack on freenode.net\nRelease Notes: http://docs.openstack.org/releasenotes/nova/",
            "date_created": "2010-07-15T17:05:00.161721+00:00",
            "homepage_url": "http://docs.openstack.org/developer/nova/",
            "wiki_url": "http://wiki.openstack.org/wiki/Nova",
            "screenshots_url": null,
            "download_url": null,
            "programming_language": "python",
            "sourceforge_project": null,
            "freshmeat_project": null,
            "brand_link": "https://api.launchpad.net/1.0/nova/brand",
            "private_bugs": false,
            "licenses": [
                "Apache Licence",
                "Simplified BSD Licence"
            ],
            "license_info": null,
            "bug_tracker_link": null,
            "date_next_suggest_packaging": null,
            "series_collection_link": "https://api.launchpad.net/1.0/nova/series",
            "development_focus_link": "https://api.launchpad.net/1.0/nova/2025.2",
            "releases_collection_link": "https://api.launchpad.net/1.0/nova/releases",
            "translation_focus_link": "https://api.launchpad.net/1.0/nova/trunk",
            "commercial_subscription_link": null,
            "commercial_subscription_is_due": false,
            "remote_product": null,
            "security_contact": null,
            "vcs": "Git",
            "http_etag": "\"c933dc867328621c23fb8e38bef2c4b32df9ebf9-3c3e9f766c0b61b4c0c1ba0094747ffe0731b177\""
            }"# }.to_string()
}

pub(crate) fn fake_bug(url: &str) -> String {
    indoc! {r#"{
            "self_link": "https://api.launchpad.net/1.0/bugs/2066153",
            "web_link": "https://bugs.launchpad.net/bugs/2066153",
            "resource_type_link": "https://api.launchpad.net/1.0/#bug",
            "id": 2066153,
            "private": false,
            "information_type": "Public",
            "name": null,
            "title": "Install and configure controller node for Red Hat Enterprise Linux and CentOS in nova",
            "description": "This bug tracker is for errors with the documentation, use the following as a template and remove or add fields as you see fit. Convert [ ] into [x] to check boxes:\n\n- [ ] This doc is inaccurate in this way: ______\n- [X] This is a doc addition request.\n- [ ] I have a fix to the document that I can paste below including example: input and output. \n\nIf you have a troubleshooting or support issue, use the following  resources:\n\n - The mailing list: https://lists.openstack.org\n - IRC: 'openstack' channel on OFTC\n\n-----------------------------------\nRelease: 29.0.2.dev8 on 2023-02-15 22:37:40\nSHA: 238c98cc988e8182da00b5081c0bcbb01e399647\nSource: https://opendev.org/openstack/nova/src/doc/source/install/controller-install-rdo.rst\nURL: https://docs.openstack.org/nova/2024.1/install/controller-install-rdo.html\n\nI have followed all the installation steps, but I can't start either the Nova Scheduler or the Nova Conductor. \n\nhttps://ibb.co/ynxFfjH",
            "owner_link": "https://api.launchpad.net/1.0/~cruzfjf",
            "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/bug_tasks",
            "duplicate_of_link": null,
            "date_created": "2024-05-20T08:50:45.545421+00:00",
            "activity_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/activity",
            "can_expire": false,
            "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/subscriptions",
            "date_last_updated": "2024-05-20T08:50:45.545421+00:00",
            "who_made_private_link": null,
            "date_made_private": null,
            "heat": 6,
            "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/bug_watches",
            "cves_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/cves",
            "vulnerabilities_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/vulnerabilities",
            "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/duplicates",
            "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/attachments",
            "security_related": false,
            "latest_patch_uploaded": null,
            "tags": [
                "doc"
            ],
            "date_last_message": "2024-05-20T08:50:45.545421+00:00",
            "number_of_duplicates": 0,
            "message_count": 1,
            "users_affected_count": 1,
            "users_unaffected_count": 0,
            "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/users_affected",
            "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/users_unaffected",
            "users_affected_count_with_dupes": 1,
            "other_users_affected_count_with_dupes": 1,
            "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/users_affected_with_dupes",
            "messages_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/messages",
            "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/2066153/linked_branches",
            "http_etag": "\"70a5d5ef114c028ebb02e03dac670c976d2e4ec9-f8d21df9cd8d5bad079fc164517f97f2b65ee4cd\""
            }"#}.to_string().replace("https://api.launchpad.net/1.0/bugs/2066153", url).replace("2066153", url.split('/').next_back().unwrap())
}

// pub(crate) fn fake_bug_tasks_page(url: &str) -> String {
//     indoc! {r#""#}.to_string()
// }

pub(crate) fn fake_bug_tasks_page_1() -> String {
    indoc! {r#"{
            "start": 0,
            "total_size": 4,
            "next_collection_link": "https://api.launchpad.net/1.0/nova?status=New&ws.op=searchTasks&ws.size=2&memo=2&ws.start=2",
            "entries": [
                {
                "self_link": "https://api.launchpad.net/1.0/nova/+bug/2093869",
                "web_link": "https://bugs.launchpad.net/nova/+bug/2093869",
                "resource_type_link": "https://api.launchpad.net/1.0/#bug_task",
                "bug_link": "https://api.launchpad.net/1.0/bugs/2093869",
                "milestone_link": null,
                "status": "New",
                "importance": "High",
                "assignee_link": null,
                "bug_target_display_name": "OpenStack Compute (nova)",
                "bug_target_name": "nova",
                "bug_watch_link": null,
                "date_assigned": null,
                "date_created": "2025-01-13T08:46:25.105013+00:00",
                "date_confirmed": null,
                "date_incomplete": null,
                "date_in_progress": null,
                "date_closed": null,
                "date_left_new": null,
                "date_triaged": null,
                "date_fix_committed": null,
                "date_fix_released": null,
                "date_left_closed": null,
                "date_deferred": null,
                "owner_link": "https://api.launchpad.net/1.0/~auniyal",
                "target_link": "https://api.launchpad.net/1.0/nova",
                "title": "Bug #2093869 in OpenStack Compute (nova): \"update conflict: Inventory for 'DISK_GB' on resource provider 'r_p-id' in use\"",
                "related_tasks_collection_link": "https://api.launchpad.net/1.0/nova/+bug/2093869/related_tasks",
                "is_complete": false,
                "http_etag": "\"e9bc46b7f993bcb29adfe145954cf0d2ac984c47-95de74425077a72215679530b17ac6df67ae008d\""
                },
                {
                "self_link": "https://api.launchpad.net/1.0/nova/+bug/2093879",
                "web_link": "https://bugs.launchpad.net/nova/+bug/2093879",
                "resource_type_link": "https://api.launchpad.net/1.0/#bug_task",
                "bug_link": "https://api.launchpad.net/1.0/bugs/2093879",
                "milestone_link": null,
                "status": "New",
                "importance": "Medium",
                "assignee_link": null,
                "bug_target_display_name": "OpenStack Compute (nova)",
                "bug_target_name": "nova",
                "bug_watch_link": null,
                "date_assigned": null,
                "date_created": "2025-01-13T12:25:15.171951+00:00",
                "date_confirmed": null,
                "date_incomplete": null,
                "date_in_progress": null,
                "date_closed": null,
                "date_left_new": null,
                "date_triaged": null,
                "date_fix_committed": null,
                "date_fix_released": null,
                "date_left_closed": null,
                "date_deferred": null,
                "owner_link": "https://api.launchpad.net/1.0/~balazs-gibizer",
                "target_link": "https://api.launchpad.net/1.0/nova",
                "title": "Bug #2093879 in OpenStack Compute (nova): \"resource tracker raises PlacementPCIException for every InventoryInUser error coming from placement via update_from_provider_tree()\"",
                "related_tasks_collection_link": "https://api.launchpad.net/1.0/nova/+bug/2093879/related_tasks",
                "is_complete": false,
                "http_etag": "\"c08338de5860cc96026e56ba679bc2421f3cc047-1b69b93bac5b4cab003162202dcb90801a46b34f\""
                }
            ]
            }"#}.to_string()
}

pub(crate) fn fake_bug_tasks_page_2() -> String {
    indoc! {r#"{
    "start": 2,
    "total_size": 4,
    "entries": [
        {
        "self_link": "https://api.launchpad.net/1.0/nova/+bug/2066206",
        "web_link": "https://bugs.launchpad.net/nova/+bug/2066206",
        "resource_type_link": "https://api.launchpad.net/1.0/#bug_task",
        "bug_link": "https://api.launchpad.net/1.0/bugs/2066206",
        "milestone_link": null,
        "status": "New",
        "importance": "Undecided",
        "assignee_link": null,
        "bug_target_display_name": "OpenStack Compute (nova)",
        "bug_target_name": "nova",
        "bug_watch_link": null,
        "date_assigned": null,
        "date_created": "2024-05-21T03:23:02.871700+00:00",
        "date_confirmed": null,
        "date_incomplete": null,
        "date_in_progress": null,
        "date_closed": null,
        "date_left_new": null,
        "date_triaged": null,
        "date_fix_committed": null,
        "date_fix_released": null,
        "date_left_closed": null,
        "date_deferred": null,
        "owner_link": "https://api.launchpad.net/1.0/~none2021",
        "target_link": "https://api.launchpad.net/1.0/nova",
        "title": "Bug #2066206 in OpenStack Compute (nova): \"Polling VM details during VM creation results in the updated_at being later in the previous detail than the later one\"",
        "related_tasks_collection_link": "https://api.launchpad.net/1.0/nova/+bug/2066206/related_tasks",
        "is_complete": false,
        "http_etag": "\"b49abaa4b8793944987c9697e221cea36c4cc0c4-43c502e4c779ed9d01c9604cc2f4aa331345a415\""
        },
        {
        "self_link": "https://api.launchpad.net/1.0/nova/+bug/2067081",
        "web_link": "https://bugs.launchpad.net/nova/+bug/2067081",
        "resource_type_link": "https://api.launchpad.net/1.0/#bug_task",
        "bug_link": "https://api.launchpad.net/1.0/bugs/2067081",
        "milestone_link": null,
        "status": "New",
        "importance": "Undecided",
        "assignee_link": null,
        "bug_target_display_name": "OpenStack Compute (nova)",
        "bug_target_name": "nova",
        "bug_watch_link": null,
        "date_assigned": null,
        "date_created": "2024-05-24T15:20:20.721018+00:00",
        "date_confirmed": null,
        "date_incomplete": null,
        "date_in_progress": null,
        "date_closed": null,
        "date_left_new": null,
        "date_triaged": null,
        "date_fix_committed": null,
        "date_fix_released": null,
        "date_left_closed": null,
        "date_deferred": null,
        "owner_link": "https://api.launchpad.net/1.0/~stuts",
        "target_link": "https://api.launchpad.net/1.0/nova",
        "title": "Bug #2067081 in OpenStack Compute (nova): \"Inconsistent Behaviour in Server List\"",
        "related_tasks_collection_link": "https://api.launchpad.net/1.0/nova/+bug/2067081/related_tasks",
        "is_complete": false,
        "http_etag": "\"3675ce96d8070bdea5ada9d19c225778bdd57a1b-43c502e4c779ed9d01c9604cc2f4aa331345a415\""
        }  ]
    }"#}.to_string()
}
